package com.miumg.copiararchivos;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.io.*;
import java.net.*;
/**
 *
 * Jenny Sofía Morales López 7690-08-6790
 * Cristian Alejandro Melgar Ordoñez 7690 21 8342
 */
public class ArchivosRemotos extends javax.swing.JFrame {
    private JButton selectFileButton;
    private JButton selectDestinationButton;
    private JButton copyButton;
    private JFileChooser fileChooser;
    private JFileChooser destinationChooser;
    private File selectedFile;
    private File destinationFile;
    private JTextField ipAddressField;
    
    
    /**
     * Creates new form ArchivosRemotos
     */
    public ArchivosRemotos() {
        super("Copiar archivos");

        selectFileButton = new JButton("Seleccionar archivo");
        selectDestinationButton = new JButton("Seleccione destino");
        copyButton = new JButton("Copiar");
        fileChooser = new JFileChooser();
        destinationChooser = new JFileChooser();
        ipAddressField = new JTextField("Ingrese la dirección IP de destino");

        selectFileButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                int returnVal = fileChooser.showOpenDialog(ArchivosRemotos.this);
                if (returnVal == JFileChooser.APPROVE_OPTION) {
                    selectedFile = fileChooser.getSelectedFile();
                }
            }
        });

        selectDestinationButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                int returnVal = destinationChooser.showSaveDialog(ArchivosRemotos.this);
                if (returnVal == JFileChooser.APPROVE_OPTION) {
                    destinationFile = destinationChooser.getSelectedFile();
                }
            }
        });

        copyButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                String ipAddress = ipAddressField.getText();
                if (selectedFile == null) {
                    JOptionPane.showMessageDialog(ArchivosRemotos.this, "Seleccione el archivo a copiar.");
                    return;
                }
                if (ipAddress.isEmpty()) {
                    JOptionPane.showMessageDialog(ArchivosRemotos.this, "Ingrese dirección IP destino.");
                    return;
                }

                try {
                    InetAddress address = InetAddress.getByName(ipAddress);
                    Socket socket = new Socket(address, 12345);

                    OutputStream outputStream = socket.getOutputStream();
                    FileInputStream fileInputStream = new FileInputStream(selectedFile);
                    byte[] buffer = new byte[1024];
                    int bytesRead;
                    while ((bytesRead = fileInputStream.read(buffer)) != -1) {
                        outputStream.write(buffer, 0, bytesRead);
                    }

                    fileInputStream.close();
                    outputStream.close();
                    socket.close();

                    JOptionPane.showMessageDialog(ArchivosRemotos.this, "Archivo copiado correctamente.");
                } catch (IOException ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(ArchivosRemotos.this, "Error al copiar archivo.");
                }
            }
        });

        JPanel panel = new JPanel(new GridLayout(5, 1));
        panel.add(selectFileButton);
        panel.add(selectDestinationButton);
        panel.add(ipAddressField);
        panel.add(copyButton);
        add(panel);

        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(400, 200);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArchivosRemotos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArchivosRemotos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArchivosRemotos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArchivosRemotos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArchivosRemotos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
